# Generated by Django 5.0.3 on 2024-03-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripción')),
                ('address', models.CharField(max_length=150, verbose_name='dirección')),
                ('images', models.ImageField(upload_to='house', verbose_name='imágenes')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'casa',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripción')),
                ('images', models.ImageField(upload_to='rooms', verbose_name='imágenes')),
            ],
            options={
                'verbose_name': 'habitación',
                'verbose_name_plural': 'habitaciones',
            },
        ),
    ]
