# Generated by Django 5.0.3 on 2024-03-08 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'casa', 'verbose_name_plural': 'casa'},
        ),
        migrations.RenameField(
            model_name='house',
            old_name='description',
            new_name='about',
        ),
        migrations.AddField(
            model_name='house',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo'),
        ),
        migrations.AddField(
            model_name='room',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='room',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.house', verbose_name='casa'),
        ),
        migrations.AddField(
            model_name='room',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición'),
        ),
        migrations.AlterField(
            model_name='house',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='house',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición'),
        ),
    ]
