# Generated by Django 5.0.3 on 2024-03-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_house_options_rename_description_house_about_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='services',
            field=models.ManyToManyField(related_name='get_rooms', to='services.service', verbose_name='servicios'),
        ),
    ]
