# Generated by Django 5.0.3 on 2024-03-11 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_services'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_rooms', to='rooms.house', verbose_name='casa'),
        ),
        migrations.AlterField(
            model_name='room',
            name='services',
            field=models.ManyToManyField(related_name='get_services', to='services.service', verbose_name='servicios'),
        ),
    ]
